<?php

namespace App\Models;

use function explode;
use function preg_replace;
use function strtolower;

trait SimontokClassTrait
{
    function __call($method, $parameters)
    {
        $method_name = strtolower(preg_replace('/(?<!^)[A-Z]/', '_$0', $method));
        $method_name = explode('_', $method_name, 2);
        if (($method_name[0] === 'get' or $method_name[0] === 'is') and self::ATTRIBUTES[$method_name[1]] !== null) {
            $attr = $method_name[1];
            return $this->$attr;
        }
        return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }
}
